# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/sochelper.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(181, 195)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.ip_tab = QtWidgets.QWidget()
        self.ip_tab.setObjectName("ip_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.ip_tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ip_layout = QtWidgets.QVBoxLayout()
        self.ip_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.ip_layout.setObjectName("ip_layout")
        self.ip_search_v = QtWidgets.QVBoxLayout()
        self.ip_search_v.setObjectName("ip_search_v")
        self.ip_search_h = QtWidgets.QHBoxLayout()
        self.ip_search_h.setObjectName("ip_search_h")
        self.ip_search_input = QtWidgets.QLineEdit(self.ip_tab)
        self.ip_search_input.setObjectName("ip_search_input")
        self.ip_search_h.addWidget(self.ip_search_input)
        self.ip_search_button = QtWidgets.QPushButton(self.ip_tab)
        self.ip_search_button.setObjectName("ip_search_button")
        self.ip_search_h.addWidget(self.ip_search_button)
        self.ip_search_v.addLayout(self.ip_search_h)
        self.ip_layout.addLayout(self.ip_search_v)
        self.ip_providers = QtWidgets.QGridLayout()
        self.ip_providers.setObjectName("ip_providers")
        self.ip_providers.setRowStretch(0, 20)
        self.ip_layout.addLayout(self.ip_providers)
        self.verticalLayout_4.addLayout(self.ip_layout)
        self.tabWidget.addTab(self.ip_tab, "")
        self.url_tab = QtWidgets.QWidget()
        self.url_tab.setObjectName("url_tab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.url_tab)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.url_layout = QtWidgets.QVBoxLayout()
        self.url_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.url_layout.setObjectName("url_layout")
        self.url_search_v = QtWidgets.QVBoxLayout()
        self.url_search_v.setObjectName("url_search_v")
        self.url_search_h = QtWidgets.QHBoxLayout()
        self.url_search_h.setObjectName("url_search_h")
        self.url_search_input = QtWidgets.QLineEdit(self.url_tab)
        self.url_search_input.setObjectName("url_search_input")
        self.url_search_h.addWidget(self.url_search_input)
        self.url_search_button = QtWidgets.QPushButton(self.url_tab)
        self.url_search_button.setObjectName("url_search_button")
        self.url_search_h.addWidget(self.url_search_button)
        self.url_search_v.addLayout(self.url_search_h)
        self.url_layout.addLayout(self.url_search_v)
        self.url_providers = QtWidgets.QGridLayout()
        self.url_providers.setObjectName("url_providers")
        self.url_providers.setRowStretch(0, 20)
        self.url_layout.addLayout(self.url_providers)
        self.verticalLayout_8.addLayout(self.url_layout)
        self.tabWidget.addTab(self.url_tab, "")
        self.domain_tab = QtWidgets.QWidget()
        self.domain_tab.setObjectName("domain_tab")
        self.verticalLayout_81 = QtWidgets.QVBoxLayout(self.domain_tab)
        self.verticalLayout_81.setObjectName("verticalLayout_81")
        self.domain_layout = QtWidgets.QVBoxLayout()
        self.domain_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.domain_layout.setObjectName("domain_layout")
        self.domain_search_v = QtWidgets.QVBoxLayout()
        self.domain_search_v.setObjectName("domain_search_v")
        self.domain_search_h = QtWidgets.QHBoxLayout()
        self.domain_search_h.setObjectName("domain_search_h")
        self.domain_search_input = QtWidgets.QLineEdit(self.domain_tab)
        self.domain_search_input.setObjectName("domain_search_input")
        self.domain_search_h.addWidget(self.domain_search_input)
        self.domain_search_button = QtWidgets.QPushButton(self.domain_tab)
        self.domain_search_button.setObjectName("domain_search_button")
        self.domain_search_h.addWidget(self.domain_search_button)
        self.domain_search_v.addLayout(self.domain_search_h)
        self.domain_layout.addLayout(self.domain_search_v)
        self.domain_providers = QtWidgets.QGridLayout()
        self.domain_providers.setObjectName("domain_providers")
        self.domain_providers.setRowStretch(0, 20)
        self.domain_layout.addLayout(self.domain_providers)
        self.verticalLayout_81.addLayout(self.domain_layout)
        self.tabWidget.addTab(self.domain_tab, "")
        self.file_tab = QtWidgets.QWidget()
        self.file_tab.setObjectName("file_tab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.file_tab)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.file_layout = QtWidgets.QVBoxLayout()
        self.file_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.file_layout.setObjectName("file_layout")
        self.file_search_v = QtWidgets.QVBoxLayout()
        self.file_search_v.setObjectName("file_search_v")
        self.file_search_h = QtWidgets.QHBoxLayout()
        self.file_search_h.setObjectName("file_search_h")
        self.file_search_input = QtWidgets.QLineEdit(self.file_tab)
        self.file_search_input.setObjectName("file_search_input")
        self.file_search_h.addWidget(self.file_search_input)
        self.file_search_button = QtWidgets.QPushButton(self.file_tab)
        self.file_search_button.setObjectName("file_search_button")
        self.file_search_h.addWidget(self.file_search_button)
        self.file_search_v.addLayout(self.file_search_h)
        self.file_layout.addLayout(self.file_search_v)
        self.file_providers = QtWidgets.QGridLayout()
        self.file_providers.setObjectName("file_providers")
        self.file_providers.setRowStretch(0, 20)
        self.file_layout.addLayout(self.file_providers)
        self.verticalLayout_9.addLayout(self.file_layout)
        self.tabWidget.addTab(self.file_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 181, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout_SOC_Helper = QtWidgets.QAction(MainWindow)
        self.actionAbout_SOC_Helper.setObjectName("actionAbout_SOC_Helper")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout_SOC_Helper)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SOC Helper"))
        self.ip_search_button.setText(_translate("MainWindow", "Go"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ip_tab), _translate("MainWindow", "IP"))
        self.url_search_button.setText(_translate("MainWindow", "Go"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.url_tab), _translate("MainWindow", "URL"))
        self.domain_search_button.setText(_translate("MainWindow", "Go"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.domain_tab), _translate("MainWindow", "Domain"))
        self.file_search_button.setText(_translate("MainWindow", "Go"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.file_tab), _translate("MainWindow", "File Hash"))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionPreferences.setText(_translate("MainWindow", "&Preferences"))
        self.actionPreferences.setShortcut(_translate("MainWindow", "Ctrl+,"))
        self.actionQuit.setText(_translate("MainWindow", "&Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionAbout_SOC_Helper.setText(_translate("MainWindow", "&About SOC Helper"))

